<?php 

$database=[
    [
        'domanda' => "What is Lorem Ipsum?",
        'risposta' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
    ],
    [
        'domanda' => "Why do we use it?",
        'risposta' => "Curabitur hendrerit sem sapien, id sodales massa sagittis ut. Donec id tincidunt libero, id eleifend tortor. Pellentesque id erat porta, mattis orci quis, pretium sapien. Integer scelerisque id magna non scelerisque. Vestibulum malesuada lacus id ex vehicula, non mollis dolor dignissim. Suspendisse vel pretium nulla, sit amet malesuada libero. Aenean ultricies nibh vitae rutrum aliquet. Maecenas quis ante suscipit, fermentum purus in, vehicula turpis. Etiam nibh mauris, suscipit luctus malesuada vel, fringilla vitae ipsum. Nulla sed lacus ac felis aliquet tincidunt a in ante. Vivamus eget vulputate nisi.
                        Vestibulum quis ante et tellus accumsan consectetur. Vestibulum non ultrices sapien, eu tristique nulla. Maecenas auctor blandit porttitor. Phasellus nunc velit, elementum non aliquet at, mattis id arcu. Nunc sollicitudin dictum enim, eu vulputate leo. Nullam id odio dignissim, gravida elit id, varius ligula. Nulla non mauris massa.
                        Nunc ultricies egestas ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed viverra nibh est, vel malesuada tortor euismod id. Fusce egestas elit sit amet placerat dictum. Nunc et nisi id metus convallis ullamcorper. Maecenas efficitur velit a laoreet viverra. Duis nec lorem in orci convallis eleifend. Cras non odio laoreet, tristique lacus et, ultrices purus. Nulla tristique elit eget nulla rhoncus congue.
                        Aliquam venenatis sit amet nibh ac ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam faucibus imperdiet erat sed interdum. Aenean varius eu dolor non auctor. Donec vitae ligula id tellus efficitur lacinia. Cras felis risus, interdum sed leo dictum, tincidunt venenatis lectus. Cras et odio rhoncus, sagittis tortor vel, tempor leo. Suspendisse mollis libero id risus eleifend, non fermentum odio consectetur.
                        Proin ac tincidunt tortor. Sed eu ligula ante. Quisque ultricies egestas dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut dignissim nisl, non lobortis neque. Vivamus efficitur ornare leo, sed pellentesque justo faucibus gravida. Aenean metus tellus, convallis ac orci vitae, efficitur fermentum velit. Sed interdum quam nec neque tristique, in ullamcorper arcu interdum. Fusce at felis eros. Cras rutrum luctus eros, in feugiat augue semper eget. Nunc risus purus, semper sed venenatis vel, scelerisque ac ipsum. Cras mattis, dui et iaculis tempor, libero magna efficitur enim, ac lacinia lacus massa vel mi. Donec vel orci at erat facilisis porttitor.
                        Integer eu commodo orci. Cras nunc elit, varius ac felis sit amet, imperdiet rutrum lacus. Integer ullamcorper massa vitae ex venenatis condimentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed vitae interdum velit. Donec commodo luctus eleifend. Fusce eu semper est, vel dictum dolor. Sed gravida felis elit, et lobortis mi sollicitudin a. Duis at blandit lorem."
                    ],
    [
        'domanda' => "What is Lorem Ipsum?",
        'risposta' => "Suspendisse efficitur mi et nisi vehicula, sit amet aliquet nunc laoreet. Nam sit amet sodales diam. Vestibulum hendrerit fringilla ex, eget porttitor mi. In id ligula vel metus dictum interdum at ac velit. Aenean vel vehicula augue. Fusce ac tincidunt nisl. Etiam ac turpis eu quam porttitor efficitur. Proin mattis aliquam dolor eu congue.
                        Integer auctor urna at dictum facilisis. Donec rhoncus mollis tortor, vel lacinia nisl. Proin at auctor nisi. Sed condimentum, odio vel tempor pulvinar, justo lacus sodales augue, ac sodales lectus eros eu leo. Nulla vitae enim in urna semper tempus id a orci. Duis eu odio sit amet ante dignissim hendrerit nec quis libero. Nullam semper justo et venenatis aliquam. Praesent quis dapibus sem. Donec fringilla facilisis ligula, sit amet viverra diam varius id. Nulla eu eros tellus. Fusce fermentum lacus diam, ac vestibulum ex posuere sit amet. Nam pretium nec arcu vel fermentum. Etiam sit amet tortor finibus, feugiat erat quis, varius augue. Morbi sit amet mattis dolor.
                        Sed a felis eget massa blandit consectetur et in augue. Sed quis tincidunt velit. Donec volutpat lectus a libero gravida, egestas lobortis quam luctus. In vestibulum ornare aliquam. Praesent nulla lorem, consequat sit amet nulla eget, suscipit sagittis ex. Sed consectetur, mi mattis viverra malesuada, arcu odio lacinia est, quis condimentum est lectus non lacus. Curabitur sed odio commodo, lacinia magna tristique, ullamcorper velit. Phasellus sed dui convallis, mollis velit a, volutpat erat. Sed tempor ultrices magna ac porta. Donec dapibus nulla in elit euismod, id bibendum dolor tristique.
                        Nam placerat nibh quis dui facilisis, vel facilisis erat gravida. Aenean interdum, sem nec sagittis pulvinar, mauris urna hendrerit lorem, sit amet mollis diam sapien vel velit. Sed quis velit condimentum turpis auctor tristique. Donec varius nec ligula vitae molestie. Vestibulum posuere risus dui, lacinia molestie quam tincidunt a. Cras pulvinar suscipit quam, ut accumsan ipsum posuere sit amet. Integer sit amet tristique eros. Sed accumsan orci nunc, eu molestie leo cursus lobortis. Nullam pharetra, est ac blandit euismod, sem ante facilisis dui, nec euismod lacus tellus eget ipsum. Vivamus at dignissim justo, at finibus nisl. Vivamus sit amet egestas justo, nec aliquam leo. Nam mattis interdum mi eget ultricies. Nunc nec metus a elit eleifend mattis eu non nulla. Suspendisse vel libero id libero efficitur iaculis ac nec diam. Vivamus efficitur massa sed sagittis pellentesque.
                        Sed id fringilla quam. Vivamus commodo, turpis id iaculis aliquet, tortor arcu placerat lacus, id finibus nibh augue nec magna. Praesent tortor enim, venenatis in odio eu, tempor varius sapien. Nulla et vehicula massa. Maecenas non magna tincidunt, interdum mi non, ornare leo. Aenean in augue vitae ex semper porta et ut erat. Cras sed vestibulum felis. Integer viverra magna non arcu vehicula feugiat. Nulla turpis ante, varius volutpat libero at, dapibus fringilla libero. Nam sit amet tincidunt turpis.
                        Nullam euismod sapien justo, a convallis nibh iaculis ut. Maecenas auctor consequat ipsum, vitae lobortis massa cursus id. Suspendisse potenti. Praesent bibendum pretium massa, et tempus massa aliquet at. Mauris sapien diam, fermentum ac justo quis, elementum feugiat nisl. Maecenas malesuada nunc vel mi commodo, sed scelerisque enim gravida. Sed rhoncus eros ut ultricies volutpat. Aliquam risus massa, tempus eu tortor vel, lobortis bibendum mauris. Mauris sed scelerisque odio. Ut ac convallis dolor. Vestibulum tempus purus a luctus laoreet.
                        Nullam efficitur ex hendrerit nisl volutpat malesuada. Nulla viverra nunc nibh, eget maximus elit aliquet ut. Maecenas aliquam in urna ut hendrerit. Praesent porta velit quis nulla consequat, sed efficitur tellus cursus. Donec eu lectus magna. Nam eleifend nunc sed egestas aliquam. Ut ullamcorper fermentum sodales. Suspendisse et ultricies lorem. Nunc nisi magna, pellentesque quis condimentum vitae, tempor et est.
                        Pellentesque eu metus varius, aliquet sapien at, efficitur massa. Quisque sed cursus leo, ut porta mi. Sed facilisis nunc ac nisi semper auctor. Vivamus vel felis at purus congue tristique eget non libero. Praesent blandit justo a nibh viverra, eget tempor lacus aliquam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed consequat vestibulum nulla sed scelerisque. Curabitur maximus magna et velit tempor condimentum. Pellentesque sit amet diam vitae mi pretium tempor sed quis lorem. Aliquam sed lacus sem. Aliquam ante odio, rhoncus vitae ultricies a, pretium non risus.
                        Vivamus felis tellus, venenatis non eros ac, rhoncus dapibus arcu. Ut semper nunc vel aliquam congue. Integer sit amet arcu lacus. Donec non malesuada quam. Cras viverra dui euismod, feugiat libero a, porttitor leo. Quisque odio nibh, facilisis non tortor quis, tristique placerat mauris. Integer placerat lectus a feugiat pellentesque. Donec ac erat consectetur sapien egestas sagittis. Quisque convallis, metus id sagittis maximus, sem nunc laoreet urna, eu interdum felis arcu vel mauris. Mauris sit amet placerat erat, non venenatis dui. Proin vestibulum tincidunt malesuada. Quisque ultricies diam eget nisi scelerisque sollicitudin. Nam consectetur nibh elit, malesuada sagittis ex rhoncus at. Vivamus ut dolor aliquet, vulputate erat vitae, egestas lacus. Sed turpis quam, sodales sed lacus rutrum, congue condimentum metus.
                        Proin ut ipsum luctus, hendrerit diam at, auctor nunc. Fusce nunc nulla, suscipit eget lacus eget, elementum rhoncus erat. Praesent sit amet commodo est. Ut molestie euismod dolor et pretium. Morbi ac lacus ornare, vehicula ligula eu, finibus felis. Sed rhoncus, magna ac dapibus fringilla, velit enim consequat lacus, in finibus diam urna in ex. Maecenas in sem sit amet sem condimentum vulputate ut nec lectus."
                    ],
    [
        'domanda' => "Where does it come from?",
        'risposta' => "Aliquam semper justo ac turpis ultrices dictum. Quisque faucibus nisi nulla, vehicula sodales nisl rutrum sed. Quisque mattis, felis sed ultricies tincidunt, libero arcu commodo ante, et euismod ex nibh id purus. Nullam rhoncus tellus nec lorem mollis consectetur. Maecenas tristique ipsum ut aliquet laoreet. Mauris convallis rhoncus neque id molestie. Suspendisse tincidunt maximus commodo. Sed ac gravida augue, ac porttitor eros. Vivamus sed odio commodo tortor sodales hendrerit eget eget nisi. Sed fermentum et sem at tristique. Pellentesque dignissim, urna id efficitur ullamcorper, mi sem aliquet mi, et tincidunt sapien purus in sapien. Quisque viverra risus nec nisl consectetur, eget aliquet est auctor. Vivamus mollis pulvinar augue ac placerat. Praesent efficitur ut felis sed sodales. Aliquam consequat ligula faucibus feugiat varius.
                        Vivamus pharetra rutrum nisi, a dapibus est tristique a. In non scelerisque massa, eget placerat est. Quisque sapien nisl, mollis nec nunc eu, cursus facilisis ipsum. Nunc id ipsum justo. Nullam sed urna condimentum, varius nisl eget, fringilla augue. Donec at dolor neque. Etiam turpis lorem, tincidunt ut commodo vitae, hendrerit et dui. Vivamus viverra dapibus vehicula. Donec tempus, sapien mattis sagittis faucibus, urna est rutrum justo, vitae eleifend neque mi eu dolor.
                        Curabitur eleifend nisi non lacus pulvinar, vestibulum malesuada sapien condimentum. Duis sollicitudin justo ut mi placerat ultricies. Morbi ac venenatis dolor. Phasellus lorem libero, maximus ut eleifend blandit, vestibulum et ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent rhoncus lorem a sapien pellentesque, eget bibendum est finibus. Curabitur congue ultricies elit eget faucibus. Morbi rhoncus mauris neque, vitae rhoncus ante volutpat ac. Donec in mattis nisi. Aenean faucibus tristique pulvinar.
                        Morbi vel erat quis sapien aliquet gravida. Ut sed euismod ipsum, nec fermentum magna. Proin risus justo, lobortis at nunc rhoncus, volutpat fringilla sapien. Donec non ex elementum, mollis elit molestie, porttitor diam. Nam neque metus, dictum ac arcu non, commodo pharetra tortor. Sed malesuada dolor non diam rhoncus dictum. Sed pellentesque nibh vitae auctor ultricies.
                        Nunc sit amet tellus quis nibh mollis tincidunt non vitae turpis. Nunc egestas neque et erat elementum, et dapibus eros ultricies. Donec vitae turpis ut elit venenatis venenatis et sed elit. Ut ac lacus et tellus ornare iaculis in a odio. Vestibulum dictum eros vel dui tempor, nec laoreet felis bibendum. Cras accumsan facilisis urna ut accumsan. Aenean vehicula eros vitae arcu ullamcorper fringilla vel maximus nulla. Sed pellentesque purus arcu, ac feugiat magna volutpat ut. In varius id tortor ut efficitur. Ut viverra lectus lacus, eget dapibus massa finibus at. Quisque volutpat ullamcorper sem id accumsan. Donec ut risus varius, mollis mi non, faucibus felis.
                        Pellentesque augue nunc, vulputate ac dui laoreet, rutrum viverra felis. Phasellus id risus eget purus consectetur ultrices. Suspendisse ut erat vehicula, elementum odio et, ultrices erat. Integer sed lobortis diam. Mauris posuere libero a metus rhoncus, at ullamcorper enim ornare. Etiam egestas quis dolor nec fringilla. Praesent finibus justo vitae neque ullamcorper euismod.
                        Integer in consectetur tortor. Donec non libero quis quam tempor commodo sit amet sit amet felis. Morbi tempor nunc a interdum tempus. Morbi tellus ipsum, ultricies id vestibulum quis, eleifend quis tellus. Aenean congue nunc turpis, a sodales justo bibendum vitae. Duis quis tincidunt ante, eu rhoncus mauris. Nulla eleifend faucibus lorem quis scelerisque. Vestibulum mauris ipsum, hendrerit eu ex ut, pharetra vestibulum massa."
    ],
    [
        'domanda' => "What is Lorem Ipsum?",
        'risposta' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
    ],
    [
        'domanda' => "Why do we use it?",
        'risposta' => "Curabitur hendrerit sem sapien, id sodales massa sagittis ut. Donec id tincidunt libero, id eleifend tortor. Pellentesque id erat porta, mattis orci quis, pretium sapien. Integer scelerisque id magna non scelerisque. Vestibulum malesuada lacus id ex vehicula, non mollis dolor dignissim. Suspendisse vel pretium nulla, sit amet malesuada libero. Aenean ultricies nibh vitae rutrum aliquet. Maecenas quis ante suscipit, fermentum purus in, vehicula turpis. Etiam nibh mauris, suscipit luctus malesuada vel, fringilla vitae ipsum. Nulla sed lacus ac felis aliquet tincidunt a in ante. Vivamus eget vulputate nisi.
                        Vestibulum quis ante et tellus accumsan consectetur. Vestibulum non ultrices sapien, eu tristique nulla. Maecenas auctor blandit porttitor. Phasellus nunc velit, elementum non aliquet at, mattis id arcu. Nunc sollicitudin dictum enim, eu vulputate leo. Nullam id odio dignissim, gravida elit id, varius ligula. Nulla non mauris massa.
                        Nunc ultricies egestas ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed viverra nibh est, vel malesuada tortor euismod id. Fusce egestas elit sit amet placerat dictum. Nunc et nisi id metus convallis ullamcorper. Maecenas efficitur velit a laoreet viverra. Duis nec lorem in orci convallis eleifend. Cras non odio laoreet, tristique lacus et, ultrices purus. Nulla tristique elit eget nulla rhoncus congue.
                        Aliquam venenatis sit amet nibh ac ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam faucibus imperdiet erat sed interdum. Aenean varius eu dolor non auctor. Donec vitae ligula id tellus efficitur lacinia. Cras felis risus, interdum sed leo dictum, tincidunt venenatis lectus. Cras et odio rhoncus, sagittis tortor vel, tempor leo. Suspendisse mollis libero id risus eleifend, non fermentum odio consectetur.
                        Proin ac tincidunt tortor. Sed eu ligula ante. Quisque ultricies egestas dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut dignissim nisl, non lobortis neque. Vivamus efficitur ornare leo, sed pellentesque justo faucibus gravida. Aenean metus tellus, convallis ac orci vitae, efficitur fermentum velit. Sed interdum quam nec neque tristique, in ullamcorper arcu interdum. Fusce at felis eros. Cras rutrum luctus eros, in feugiat augue semper eget. Nunc risus purus, semper sed venenatis vel, scelerisque ac ipsum. Cras mattis, dui et iaculis tempor, libero magna efficitur enim, ac lacinia lacus massa vel mi. Donec vel orci at erat facilisis porttitor.
                        Integer eu commodo orci. Cras nunc elit, varius ac felis sit amet, imperdiet rutrum lacus. Integer ullamcorper massa vitae ex venenatis condimentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed vitae interdum velit. Donec commodo luctus eleifend. Fusce eu semper est, vel dictum dolor. Sed gravida felis elit, et lobortis mi sollicitudin a. Duis at blandit lorem."
                    ],
    [
        'domanda' => "What is Lorem Ipsum?",
        'risposta' => "Suspendisse efficitur mi et nisi vehicula, sit amet aliquet nunc laoreet. Nam sit amet sodales diam. Vestibulum hendrerit fringilla ex, eget porttitor mi. In id ligula vel metus dictum interdum at ac velit. Aenean vel vehicula augue. Fusce ac tincidunt nisl. Etiam ac turpis eu quam porttitor efficitur. Proin mattis aliquam dolor eu congue.
                        Integer auctor urna at dictum facilisis. Donec rhoncus mollis tortor, vel lacinia nisl. Proin at auctor nisi. Sed condimentum, odio vel tempor pulvinar, justo lacus sodales augue, ac sodales lectus eros eu leo. Nulla vitae enim in urna semper tempus id a orci. Duis eu odio sit amet ante dignissim hendrerit nec quis libero. Nullam semper justo et venenatis aliquam. Praesent quis dapibus sem. Donec fringilla facilisis ligula, sit amet viverra diam varius id. Nulla eu eros tellus. Fusce fermentum lacus diam, ac vestibulum ex posuere sit amet. Nam pretium nec arcu vel fermentum. Etiam sit amet tortor finibus, feugiat erat quis, varius augue. Morbi sit amet mattis dolor.
                        Sed a felis eget massa blandit consectetur et in augue. Sed quis tincidunt velit. Donec volutpat lectus a libero gravida, egestas lobortis quam luctus. In vestibulum ornare aliquam. Praesent nulla lorem, consequat sit amet nulla eget, suscipit sagittis ex. Sed consectetur, mi mattis viverra malesuada, arcu odio lacinia est, quis condimentum est lectus non lacus. Curabitur sed odio commodo, lacinia magna tristique, ullamcorper velit. Phasellus sed dui convallis, mollis velit a, volutpat erat. Sed tempor ultrices magna ac porta. Donec dapibus nulla in elit euismod, id bibendum dolor tristique.
                        Nam placerat nibh quis dui facilisis, vel facilisis erat gravida. Aenean interdum, sem nec sagittis pulvinar, mauris urna hendrerit lorem, sit amet mollis diam sapien vel velit. Sed quis velit condimentum turpis auctor tristique. Donec varius nec ligula vitae molestie. Vestibulum posuere risus dui, lacinia molestie quam tincidunt a. Cras pulvinar suscipit quam, ut accumsan ipsum posuere sit amet. Integer sit amet tristique eros. Sed accumsan orci nunc, eu molestie leo cursus lobortis. Nullam pharetra, est ac blandit euismod, sem ante facilisis dui, nec euismod lacus tellus eget ipsum. Vivamus at dignissim justo, at finibus nisl. Vivamus sit amet egestas justo, nec aliquam leo. Nam mattis interdum mi eget ultricies. Nunc nec metus a elit eleifend mattis eu non nulla. Suspendisse vel libero id libero efficitur iaculis ac nec diam. Vivamus efficitur massa sed sagittis pellentesque.
                        Sed id fringilla quam. Vivamus commodo, turpis id iaculis aliquet, tortor arcu placerat lacus, id finibus nibh augue nec magna. Praesent tortor enim, venenatis in odio eu, tempor varius sapien. Nulla et vehicula massa. Maecenas non magna tincidunt, interdum mi non, ornare leo. Aenean in augue vitae ex semper porta et ut erat. Cras sed vestibulum felis. Integer viverra magna non arcu vehicula feugiat. Nulla turpis ante, varius volutpat libero at, dapibus fringilla libero. Nam sit amet tincidunt turpis.
                        Nullam euismod sapien justo, a convallis nibh iaculis ut. Maecenas auctor consequat ipsum, vitae lobortis massa cursus id. Suspendisse potenti. Praesent bibendum pretium massa, et tempus massa aliquet at. Mauris sapien diam, fermentum ac justo quis, elementum feugiat nisl. Maecenas malesuada nunc vel mi commodo, sed scelerisque enim gravida. Sed rhoncus eros ut ultricies volutpat. Aliquam risus massa, tempus eu tortor vel, lobortis bibendum mauris. Mauris sed scelerisque odio. Ut ac convallis dolor. Vestibulum tempus purus a luctus laoreet.
                        Nullam efficitur ex hendrerit nisl volutpat malesuada. Nulla viverra nunc nibh, eget maximus elit aliquet ut. Maecenas aliquam in urna ut hendrerit. Praesent porta velit quis nulla consequat, sed efficitur tellus cursus. Donec eu lectus magna. Nam eleifend nunc sed egestas aliquam. Ut ullamcorper fermentum sodales. Suspendisse et ultricies lorem. Nunc nisi magna, pellentesque quis condimentum vitae, tempor et est.
                        Pellentesque eu metus varius, aliquet sapien at, efficitur massa. Quisque sed cursus leo, ut porta mi. Sed facilisis nunc ac nisi semper auctor. Vivamus vel felis at purus congue tristique eget non libero. Praesent blandit justo a nibh viverra, eget tempor lacus aliquam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed consequat vestibulum nulla sed scelerisque. Curabitur maximus magna et velit tempor condimentum. Pellentesque sit amet diam vitae mi pretium tempor sed quis lorem. Aliquam sed lacus sem. Aliquam ante odio, rhoncus vitae ultricies a, pretium non risus.
                        Vivamus felis tellus, venenatis non eros ac, rhoncus dapibus arcu. Ut semper nunc vel aliquam congue. Integer sit amet arcu lacus. Donec non malesuada quam. Cras viverra dui euismod, feugiat libero a, porttitor leo. Quisque odio nibh, facilisis non tortor quis, tristique placerat mauris. Integer placerat lectus a feugiat pellentesque. Donec ac erat consectetur sapien egestas sagittis. Quisque convallis, metus id sagittis maximus, sem nunc laoreet urna, eu interdum felis arcu vel mauris. Mauris sit amet placerat erat, non venenatis dui. Proin vestibulum tincidunt malesuada. Quisque ultricies diam eget nisi scelerisque sollicitudin. Nam consectetur nibh elit, malesuada sagittis ex rhoncus at. Vivamus ut dolor aliquet, vulputate erat vitae, egestas lacus. Sed turpis quam, sodales sed lacus rutrum, congue condimentum metus.
                        Proin ut ipsum luctus, hendrerit diam at, auctor nunc. Fusce nunc nulla, suscipit eget lacus eget, elementum rhoncus erat. Praesent sit amet commodo est. Ut molestie euismod dolor et pretium. Morbi ac lacus ornare, vehicula ligula eu, finibus felis. Sed rhoncus, magna ac dapibus fringilla, velit enim consequat lacus, in finibus diam urna in ex. Maecenas in sem sit amet sem condimentum vulputate ut nec lectus."
                    ],
    [
        'domanda' => "Where does it come from?",
        'risposta' => "Aliquam semper justo ac turpis ultrices dictum. Quisque faucibus nisi nulla, vehicula sodales nisl rutrum sed. Quisque mattis, felis sed ultricies tincidunt, libero arcu commodo ante, et euismod ex nibh id purus. Nullam rhoncus tellus nec lorem mollis consectetur. Maecenas tristique ipsum ut aliquet laoreet. Mauris convallis rhoncus neque id molestie. Suspendisse tincidunt maximus commodo. Sed ac gravida augue, ac porttitor eros. Vivamus sed odio commodo tortor sodales hendrerit eget eget nisi. Sed fermentum et sem at tristique. Pellentesque dignissim, urna id efficitur ullamcorper, mi sem aliquet mi, et tincidunt sapien purus in sapien. Quisque viverra risus nec nisl consectetur, eget aliquet est auctor. Vivamus mollis pulvinar augue ac placerat. Praesent efficitur ut felis sed sodales. Aliquam consequat ligula faucibus feugiat varius.
                        Vivamus pharetra rutrum nisi, a dapibus est tristique a. In non scelerisque massa, eget placerat est. Quisque sapien nisl, mollis nec nunc eu, cursus facilisis ipsum. Nunc id ipsum justo. Nullam sed urna condimentum, varius nisl eget, fringilla augue. Donec at dolor neque. Etiam turpis lorem, tincidunt ut commodo vitae, hendrerit et dui. Vivamus viverra dapibus vehicula. Donec tempus, sapien mattis sagittis faucibus, urna est rutrum justo, vitae eleifend neque mi eu dolor.
                        Curabitur eleifend nisi non lacus pulvinar, vestibulum malesuada sapien condimentum. Duis sollicitudin justo ut mi placerat ultricies. Morbi ac venenatis dolor. Phasellus lorem libero, maximus ut eleifend blandit, vestibulum et ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent rhoncus lorem a sapien pellentesque, eget bibendum est finibus. Curabitur congue ultricies elit eget faucibus. Morbi rhoncus mauris neque, vitae rhoncus ante volutpat ac. Donec in mattis nisi. Aenean faucibus tristique pulvinar.
                        Morbi vel erat quis sapien aliquet gravida. Ut sed euismod ipsum, nec fermentum magna. Proin risus justo, lobortis at nunc rhoncus, volutpat fringilla sapien. Donec non ex elementum, mollis elit molestie, porttitor diam. Nam neque metus, dictum ac arcu non, commodo pharetra tortor. Sed malesuada dolor non diam rhoncus dictum. Sed pellentesque nibh vitae auctor ultricies.
                        Nunc sit amet tellus quis nibh mollis tincidunt non vitae turpis. Nunc egestas neque et erat elementum, et dapibus eros ultricies. Donec vitae turpis ut elit venenatis venenatis et sed elit. Ut ac lacus et tellus ornare iaculis in a odio. Vestibulum dictum eros vel dui tempor, nec laoreet felis bibendum. Cras accumsan facilisis urna ut accumsan. Aenean vehicula eros vitae arcu ullamcorper fringilla vel maximus nulla. Sed pellentesque purus arcu, ac feugiat magna volutpat ut. In varius id tortor ut efficitur. Ut viverra lectus lacus, eget dapibus massa finibus at. Quisque volutpat ullamcorper sem id accumsan. Donec ut risus varius, mollis mi non, faucibus felis.
                        Pellentesque augue nunc, vulputate ac dui laoreet, rutrum viverra felis. Phasellus id risus eget purus consectetur ultrices. Suspendisse ut erat vehicula, elementum odio et, ultrices erat. Integer sed lobortis diam. Mauris posuere libero a metus rhoncus, at ullamcorper enim ornare. Etiam egestas quis dolor nec fringilla. Praesent finibus justo vitae neque ullamcorper euismod.
                        Integer in consectetur tortor. Donec non libero quis quam tempor commodo sit amet sit amet felis. Morbi tempor nunc a interdum tempus. Morbi tellus ipsum, ultricies id vestibulum quis, eleifend quis tellus. Aenean congue nunc turpis, a sodales justo bibendum vitae. Duis quis tincidunt ante, eu rhoncus mauris. Nulla eleifend faucibus lorem quis scelerisque. Vestibulum mauris ipsum, hendrerit eu ex ut, pharetra vestibulum massa."
                    ]
];


?>



<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">

            <link rel="preconnect" href="https://fonts.gstatic.com">
            <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">

            <link rel="stylesheet" href="css/style.css">
            <title>Google faq</title>
        </head>
        <body>
            
            <div class="content">
                 <h1>Google faq</h1>

                <ul>
                <?php 
                    foreach ($database as $value) {
                        echo "<li>
                                <h2> ".$value['domanda']."</h2>
                                <p>".$value['risposta']."</p>
                            </li>";
                    }
                ?>
                </ul>
            </div>
        </body>
    </html>